name: Example Arbor Exfil
description: Run read-only ArbOS commands to collect diagnostics
commands:
  - command: show version
  - command: show device status
  - command: show routes
    timeout: 45s

